### PR TITLE
Add tutorial on AB-joins

### PR DESCRIPTION
**Pull request by MokaPot**
# Pull Request Checklist

Below is a simple checklist but please do not hesitate to ask for assistance!

- [x] Fork, clone, and checkout the newest version of the code
- [x] Create a new branch
- [x] Make necessary code changes
- [x] Install `black` (i.e., `python -m pip install black` or `conda install black`)
- [x] Install `flake8` (i.e., `python -m pip install flake8` or `conda install flake8`)
- [x] Install `pytest-cov` (i.e., `python -m pip install pytest-cov` or `conda install pytest-cov`)
- [ ] Run `black .` in the root stumpy directory
- [ ] Run `flake8 .` in the root stumpy directory
- [ ] Run `./setup.sh && ./test.sh` in the root stumpy directory
- [ ] Reference a Github issue (and create one if one doesn't already exist)

This resolves issue #257

### CODE REVIEW

**Comment by seanlaw** [comment]
@MokaPot Thank you for contributing this tutorial! I will need some time to go over it in a little more detail but it looks great so far! Well done! Below are thoughts for you to consider and I leave it up to you to accept/reject but know that I will not take any offense if you disagree. I really appreciate your time on this!

My first suggestion would be to include this short YouTube video when you describe the lawsuit and encourage the user to watch it. One can certainly hear the similarities but how do you spot these similarities programmatically? Then, show the plots and how it is hard to extract similarities but STUMPY can help. Then, after we find the motif then we should relate it back to the original storyline. Right now, it ends rather abruptly so a callback to the original goal would be good.

Finally, it would be nice to have a final "summary" paragraph that points out other potential applications. This will help inspire others to use it. Sometimes, users can have tunnel vision and think that AB-joins can only be used for analyzing music frequencies but, in reality, there is a wide range on interesting applications.

Would you mind removing the timing and its comparison to the paper? The Matrix Profile I paper uses a slower algorithm than STUMPY and so it isn't particularly fair to that paper to compare the computational time in this case. It is also a bit distracting in this particular case.

**Comment by seanlaw** [comment]
@MokaPot I usually announce new STUMPY releases on Twitter. Do you happen to have a Twitter handle so that I can acknowledge your contributions publicly? If not perhaps a first and last name that I can use? Absolutely no pressure though.

**Comment by MokaPot** [comment]
@seanlaw Thanks for the feedback Sean :) . I've made all of the suggested changes. 

I've shortened the distance between the introduction (and video) and the plots of the raw DFCCs by removing the pandas  heads. However it's still quite distant, I could insert them as images nearer the top? Or grab some from the original paper/presentations?

I've put some quite vague examples in the conclusion. Are you happy to modify? I feel they are a little weak (I only started reading about stumpy last Friday).  

I've run the tests, in the auto generated tick list but get some issues. I assume for a notebook update this is not as important? black suggest it had modify 60+ files and the testing failed because I don't have dask installed.

My twitters very sparse but ou can find me at '@mokapotross' / Ross McCullough.

Thanks for your feedback and time, I've learnt alot today :)

**Comment by seanlaw** [comment]
Thanks, @MokaPot! I will take a look.

P.S. I couldn't seem to locate you on Twitter using the "mokapotross" handle

**Comment by seanlaw** [comment]
> I've put some quite vague examples in the conclusion. Are you happy to modify? 

Yes, you've done more than enough and I think I can take it from here! If you're good with it, I'd like to merge this PR and I can work on refining it on my end. How does that sound @MokaPot?

**Comment by MokaPot** [comment]
@seanlaw perfect! I'm happy to start looking at some of the 100 questions? I'll drop a comment on the issue later.

**Comment by seanlaw** [comment]
> I'm happy to start looking at some of the 100 questions? I'll drop a comment on the issue later.

Sounds good. Before you start any coding for the "100 Questions" make sure to run it by me first as I would hate for you to put time into it and having it not be used. If something catches your eye then just spin up a new issue, describe what the example is and where to find the data, and I can take a look and give you the green/red light. In fact, similar to this AB-join notebook, I think it would be a ton of help if we simply had a bunch of starter notebooks available that simply retrieves the data and stops. Those would be great for other "first time contributors" to contribute to.  Often times, the hardest part is overcoming the friction of retrieving the data but if we can handle that part and allow others to build out the Tutorial by calling STUMPY API functions then it would reduce the barrier to entry. Just a thought. I am flexible

 And, thanks again, for contributing to our community!

**Comment by MokaPot** [comment]
Sounds like a good idea. I definitely don't want to pinch all first timer issues, this kind of problem was a real confidence booster for me to finally get involved in open source. Cheers for your help.

**Pull request merged**
