### PR TITLE
Fix 895 update unit test

### LINKED ISSUE #895: `test_precision` is missing in uni test `test.sh`

### PR DESCRIPTION
**Pull request by NimaSarajpoor**
This PR fixes #895

### CODE REVIEW

**Comment by seanlaw** [comment]
I can't remember why but for unit tests, they must be listed out as shown rather than the way that you had simplified.

**Comment by seanlaw** [comment]
I noticed that it took 2 h and 37 mins to run...

Re-running again

**Comment by NimaSarajpoor** [comment]
> It may have been because of `dask` or `gpu`-related functions

I was trying to see if I could find any difference in the commands in the shell script when it needs to run on GPU but couldn't find anything. 

> Can you confirm that all tests are being executed in test_unit and that there are no side effects on colab?

(1) I will check the logs
(2) I will test it on colab

**Comment by seanlaw** [comment]
> I tried to see if I could find any difference in the commands in the shell script when a test needs to run on GPU but couldn't find anything. [so, I thought a for-loop should be safe]

What I would do is check that the number of tests being executed for each file is the same with/without the for-loop. For example, `test_aamp.py` says `27 passed in 21.45s`. This needs to be the same for all `test_x.py` files in both non-for-loop and for-loop scenarios.

**Comment by NimaSarajpoor** [comment]
> . This needs to be the same for all `test_x.py` files in both non-for-loop and for-loop scenarios.

They are the same (I compared one unit testing check in for-loop scenario with one unit testing check in non-for-loop scenario, and I checked the counts of tests being passed/skipped in each `test_*.py` file)

---

Also: these new tests will be covered after the merge:
* test_chain.py
* test_floss.py
* test_stamp.py
* test_stomp.py (discontinued?)

**Comment by NimaSarajpoor** [comment]
> Next task: check colab

Done! All tests are passing and they were compared with the outcome of running `./test.sh` in branch main. All good.

**Comment by seanlaw** [comment]
Thanks @NimaSarajpoor for the refactor. We may be able to simplify this down further

**Pull request merged**
