### PR TITLE
Change variable names in tests

### PR DESCRIPTION
**Pull request by sergiobuj**
This patch changes the references of left/right, as discussed in TDAmeritrade/stumpy#235.

This PR (the first) includes the most straightforward changes.

---

Checklist:
- I was able to get`./setup.sh && ./test.sh ` to run without issues.

### CODE REVIEW

**Comment by seanlaw** [comment]
Thank you @sergiobuj! I will take a look

**Comment by seanlaw** [comment]
Out of curiosity, was this a painful manual process or a simpler "search-and-replace"?

**Comment by sergiobuj** [comment]
> Out of curiosity, was this a painful manual process or a simpler "search-and-replace"?

@seanlaw I doing something in between. I'm using the "multiple selection" and "multiple cursors" features in VS Code to modify multiple occurrences in each test at the same time.

**Review by seanlaw — COMMENTED** [review]
@sergiobuj Everything looks good to me and all tests are passing! I think this is ready to merge. Thank you for taking the time to contribute to our project! I really appreciate it

**Pull request merged**
