### PR TITLE
revise `gpu_stump` for sake of consistency

### PR DESCRIPTION
**Pull request by NimaSarajpoor**
This PR revises `gpu_stump` to make it more readable.

### CODE REVIEW

**Comment by NimaSarajpoor** [comment]
@seanlaw 
`gpu_stump` passes tests in `GPU` mode.

**Comment by seanlaw** [comment]
Looks good @NimaSarajpoor. Can I merge it?

**Comment by NimaSarajpoor** [comment]
I think it is good too! Please feel free to merge it.

**Comment by seanlaw** [comment]
@NimaSarajpoor Thank you for addressing this and making things more consistent1

**Pull request merged**
