### PR TITLE
Fixed #652 Improve Docstrings

### LINKED ISSUE #652: Incorrect descriptions in Docstrings
I have been reading the module `mpdist` and I noticed:

* The description of the output of `_mpdist_vect` is missing from its docstring
* The description of `μ_Q` and `σ_Q` (in `_mpdist_vect`) are not correct. I think they should be `numpy.ndarrays` not `float`.
* The description of `μ_Q` and `σ_Q` (in `core. _mass_distance_matrix`) are not correct. I think they should be `numpy.ndarrays` not `float`.

### PR DESCRIPTION
**Pull request by NimaSarajpoor**
This PR addresses issue #652

### CODE REVIEW

**Comment by seanlaw** [comment]
Thanks @NimaSarajpoor. Looks like there is a failing test 😢

**Comment by NimaSarajpoor** [comment]
> Looks like there is a failing test

Yeah I noticed that. Although the changes I made were just on docstrings. it is good that the issue reveals itself. It is not related to this PR. But, if I can find it, I resolve it here in this PR. Is that okay?

**Comment by NimaSarajpoor** [comment]
@seanlaw 
So, I took a look at the error:
```
ref_mp = naive.stumpi_egress(T, m)
ref_P = ref_mp.P_.copy()

stream = stumpi(T, m, egress=True)
comp_P = stream.P_.copy()

npt.assert_almost_equal(ref_P, comp_P, decimal=config.STUMPY_TEST_PRECISION) # Error!
```
However, both `stumpi`  and its naive version `naive.stumpi_egress` use the performant version `stump` to calculate the initial matrix profile for time series `T` and length `m`. So, we should have got the same result. Is it possible that we have two different imprecisions for the same process with same input? 

I took a look at the naive version again, and the only difference is that the naive version of stumpi does `stump(T, m)` instead of `stump(self._T, self._m)`.  Although that is most likely not the cause of error, I changed it to `self._T` and `self._m`. I ran 50 tests (i.e. 50 iterations) for that particular `test_functions` and I got no error. What do you think?

**Comment by seanlaw** [comment]
@NimaSarajpoor I ran the test multiple times with different random seeds and was able to make it error out with

```
def test_stumpi_identical_subsequence_self_join_egress():
    m = 3

    seed = np.random.randint(100000)
    seed = 84451
    np.random.seed(seed)
```

It's not the exact same array but I think it's sufficiently similar. Does this help?

**Comment by NimaSarajpoor** [comment]
Yes! Thanks for the seed :) I will investigate it.

**Comment by NimaSarajpoor** [comment]
@seanlaw 
I think the error is not related to `stumpi`, and it is in fact related to `stumpy.stump`. In below, I showed part of the test function where the error happens.

```
# in tests/test_stumpi.py
# in test_stumpi_identical_subsequence_self_join_egress

ref_mp = naive.stumpi_egress(T, m)
ref_P = ref_mp.P_.copy()

stream = stumpi(T, m, egress=True)
comp_P = stream.P_.copy()
 
naive.replace_inf(ref_P)
naive.replace_inf(comp_P)    
>       npt.assert_almost_equal(ref_P, comp_P, decimal=config.STUMPY_TEST_PRECISION)

```
As you can see, the error is between `ref_P` and `comp_P`. These are in fact the matrix profile of time series `T` and parameter ` m`  (see the class `stumpi`/`__init__` method). The error happens because `stumpy.stump` and `naive.stump` have different outputs in this case. 

So, I started investigating `stumpy.stump` and I realized the calculated `ρ` between identical subsequences is not exactly 1 (due to imprecision in calculation). And, in this case, it is slightly more than 1 (e.g. `1.0000000000280238`) Apparently, this error is similar to issue #610. In that issue, the problem was that the value of `ρ` between two identical was not 1, and in that case, it was below 1. It was  `0.9999999999483034`.

If we go with the solution you proposed in issue #610, i.e. adding the computationally cheap `if-block`:
```
if pearson > config.STUMPY_PERFECT_CORRELATION:
            pearson = 1.0
```
we can solve both issues. I tested it with `config.STUMPY_PERFECT_CORRELATION = 0.99999999`

**Comment by seanlaw** [comment]
Awesome find! Would you mind adding BOTH unit tests (with the fixed random seed), adding the `config` variable, and submitting a PR?

**Comment by NimaSarajpoor** [comment]
> Would you mind adding BOTH unit tests (with the fixed random seed), adding the `config` variable, add the if-else to `naive.stump`, and submitting a PR?

Cool. Will do so shortly!

**Comment by seanlaw** [comment]
@NimaSarajpoor  If it's okay with you, since this is being tracked in the other PR, I will merge this commit.

**Comment by NimaSarajpoor** [comment]
> @NimaSarajpoor If it's okay with you, since this is being tracked in the other PR, I will merge this commit.

Sure. Thanks for letting me know.

**Comment by seanlaw** [comment]
Thanks @NimaSarajpoor!

**Pull request merged**
