### PR TITLE
Fixed #1010 pull request checklist

### LINKED ISSUE #1010: Update pull request checklist to align with updated contribution requirements (i.e. for black, flake8, ./setup.sh and ./test.sh)
The current checklist for opening a pull request conflicts with the contributing guide. The contributing guide is as follows...
image

While the pull request checklist is as follows...
```
# Pull Request Checklist

Below is a simple checklist but please do not hesitate to ask for assistance!

- [x] Fork, clone, and checkout the newest version of the code
- [x] Create a new branch
- [x] Make necessary code changes
- [x] Install `black` (i.e., `python -m pip install black` or `conda install -c conda-forge black`)
- [x] Install `flake8` (i.e., `python -m pip install flake8` or `conda install -c conda-forge flake8`)
- [x] Install `pytest-cov` (i.e., `python -m pip install pytest-cov` or `conda install -c conda-forge pytest-cov`)
- [x] Run `black .` in the root stumpy directory
- [x] Run `flake8 .` in the root stumpy directory
- [x] Run `./setup.sh && ./test.sh` in the root stumpy directory
- [x] Reference a Github issue (and create one if one doesn't already exist)

```

The pull request checklist should be updated to reflect recent changes surrounding running black, flake8 and ./setup.sh as well as ./test.sh.

### PR DESCRIPTION
**Pull request by joehiggi1758**
# Pull Request Checklist

Below is a simple checklist but please do not hesitate to ask for assistance!

- [x] Fork, clone, and checkout the newest version of the code
- [x] Create a new branch
- [x] Make necessary code changes
- [x] Install `black` (i.e., `python -m pip install black` or `conda install -c conda-forge black`)
- [x] Install `flake8` (i.e., `python -m pip install flake8` or `conda install -c conda-forge flake8`)
- [x] Install `pytest-cov` (i.e., `python -m pip install pytest-cov` or `conda install -c conda-forge pytest-cov`)
- [x] Run `black .` in the root stumpy directory
- [x] Run `flake8 .` in the root stumpy directory
- [x] Run `./setup.sh && ./test.sh` in the root stumpy directory
- [x] Reference a Github issue (and create one if one doesn't already exist)

### CODE REVIEW

**Review by seanlaw — COMMENTED** [review]
Everything looks good @joehiggi1758. Is this ready to be merged?

**Comment by joehiggi1758** [comment]
It is! @seanlaw

**Comment by seanlaw** [comment]
Thank you @joehiggi1758! 🎉

**Comment by joehiggi1758** [comment]
Many thanks for the opportunity @seanlaw !

**Pull request merged**
