### PR TITLE
Set notebook structure and implemented KTIP algorithm

### PR DESCRIPTION
**Pull request by joehiggi1758**
# Pull Request Checklist

Below is a simple checklist but please do not hesitate to ask for assistance!

- [x] Fork, clone, and checkout the newest version of the code
- [x] Create a new branch
- [x] Make necessary code changes
- [x] Install `black` (i.e., `python -m pip install black` or `conda install -c conda-forge black`)
- [x] Install `flake8` (i.e., `python -m pip install flake8` or `conda install -c conda-forge flake8`)
- [x] Install `pytest-cov` (i.e., `python -m pip install pytest-cov` or `conda install -c conda-forge pytest-cov`)
- [x] Run `black --exclude=".*\.ipynb" --extend-exclude=".venv" --diff ./` in the root stumpy directory
- [x] Run `flake8 --extend-exclude=.venv ./` in the root stumpy directory
- [x] Run `./setup.sh dev && ./test.sh` in the root stumpy directory
- [x] Reference a Github issue (and create one if one doesn't already exist)

### CODE REVIEW

**Comment by seanlaw** [comment]
@joehiggi1758 I know that this is still a work-in-progress but this looks fantastic! I haven't gone over things in detail but, at a high level, I really like how you're breaking everything down in consumable chunks and also explaining each part very clearly.  Please leave me a comment when you think it is ready for any type of feedback or if you had any questions. Great job so far!

**Comment by joehiggi1758** [comment]
@seanlaw hope you're having a great one!

I've been fairly busy with work lately, but still wanted to move this forward! 

I'm about 85% there, the full MOMP implementation isn't working yet - but open to your feedback up to this point on the structure, breakdown and implementation of each sub function!

**Comment by seanlaw** [comment]
Thanks @joehiggi1758 and no problem on any delays. Please allow me some time to review it and provide feedback.

**Comment by seanlaw** [comment]
Moved to #1046

**Pull request closed without merging**
