### PR TITLE
MPdist documentation

### PR DESCRIPTION
**Pull request by Deepakgthomas**

### CODE REVIEW

**Comment by seanlaw** [comment]
@Deepakgthomas It looks like you aren't getting any errors now. Can you try looking at this [supplementary section of their paper](https://sites.google.com/site/mpdistinfo/) for data from the paper?  I don't love the idea of using the name example (i.e., Beth, Lisa, Mary) as it isn't really a time series and it will be too detached from reality. 

In section A of their paper, they use [electrical power demand time series](https://pureportal.strath.ac.uk/en/datasets/refit-electrical-load-measurements-cleaned) data that is also referenced in 12 of their paper. The website for the data, REFIT, looks to be [available here] (https://www.refitsmarthomes.org/datasets/). This might be a good place to explore

**Comment by Deepakgthomas** [comment]
I'm working on this and I guess I should have something by the end of this week. I just started on my PhD and hence things are getting a little hectic :)

**Comment by seanlaw** [comment]
Thanks for letting me know and good luck with the start of your PhD! There is no rush as we are keen on getting this foundation right. Let me know if there is anything I can do to help.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Deepakgthomas** [comment]
Thank you!

**Comment by seanlaw** [comment]
@Deepakgthomas Do you mind if we close this PR for now since it isn't completed and resubmit when you've made progress? I may be able to find some time to work on this in the near future.

**Comment by Deepakgthomas** [comment]
That works for me!!

**Pull request closed without merging**
