### PR TITLE
docs: Add NumFOCUS Affiliated Project to README

### PR DESCRIPTION
**Pull request by matthewfeickert**
# Pull Request Checklist

:wave: After seeing the [NumFOCUS Tweet](https://twitter.com/NumFOCUS/status/1771265597248016553) that welcomed STUMPY to NumFOCUS Affiliated Project I checked out the project and noticed that there isn't a badge or notice on the README yet. So hi and welcome to the Affiliated Projects from the `pyhf` dev team! :)

[NumFOCUS Affiliated Project](https://numfocus.org/sponsored-projects/affiliated-projects)

* STUMPY became a NumFOCUS Affiliated Project on in March, 2024.
   - c.f. https://numfocus.org/sponsored-projects/affiliated-projects

Below is a simple checklist but please do not hesitate to ask for assistance!

- [X] Fork, clone, and checkout the newest version of the code
- [x] Create a new branch
- [x] Make necessary code changes
- [N/A] Install `black` (i.e., `python -m pip install black` or `conda install -c conda-forge black`)
- [N/A] Install `flake8` (i.e., `python -m pip install flake8` or `conda install -c conda-forge flake8`)
- [N/A] Install `pytest-cov` (i.e., `python -m pip install pytest-cov` or `conda install -c conda-forge pytest-cov`)
- [N/A] Run `black .` in the root stumpy directory
- [N/A] Run `flake8 .` in the root stumpy directory
- [N/A] Run `./setup.sh && ./test.sh` in the root stumpy directory
- [N/A] Reference a Github issue (and create one if one doesn't already exist)

### CODE REVIEW

**Comment by matthewfeickert** [comment]
cc @seanlaw for review.

**Comment by seanlaw** [comment]
Thank you @matthewfeickert. Maybe this is a chicken-and-the-egg situation but should we wait until NumFOCUS adds the STUMP project/logo to their affiliation page first? Otherwise, it may look like we are claiming affiliation via the badge but the official NumFOCUS page shows no confirmation. Maybe I'm overthinking this...

**Review by seanlaw — COMMENTED** [review]
Everything looks good to me! Thank you for the PR

**Comment by seanlaw** [comment]
> Thank you @matthewfeickert. Maybe this is a chicken-and-the-egg situation but should we wait until NumFOCUS adds the STUMP project/logo to their affiliation page first? Otherwise, it may look like we are claiming affiliation via the badge but the official NumFOCUS page shows no confirmation. Maybe I'm overthinking this...

Ohh, never mind! It looks like it was added to the bottom of the affiliated projects page (rather than in alphabetical order)

**Comment by seanlaw** [comment]
@matthewfeickert Would you happen to know why the badges are now arranged one per line in the README?

Screenshot 2024-03-30 at 5 57 13 PM

Interestingly, it looks fine at [readthedocs](https://stumpy.readthedocs.io/en/latest/):

Screenshot 2024-03-30 at 5 58 54 PM

**Comment by matthewfeickert** [comment]
@seanlaw Short answer is no, but I think it has something to do with the changes GitHub is making internally at the moement that it affects other projects beyond STUMPY (c.f. https://github.com/jaraco/pytest-checkdocs).

The being said, it seems to only affect READMEs where all the badges are included in a single line like

https://github.com/TDAmeritrade/stumpy/blob/f69b6198472041fd28cdb5f23419df11e44103af/README.rst?plain=1#L1-L39

but for projects like `pyhf` where we [break our badges up across multiple groupings/lines](https://github.com/scikit-hep/pyhf/blob/39db83b8df8d3bd6c52b974332a1833727c8fa07/README.rst?plain=1#L9-L18) it [doesn't happen](https://github.com/scikit-hep/pyhf/blob/39db83b8df8d3bd6c52b974332a1833727c8fa07/README.rst).

**Comment by seanlaw** [comment]
That worked! Thank you for the tip @matthewfeickert

**Pull request merged**
