### PR TITLE
Use official OSI name in the license metadata

### PR DESCRIPTION
**Pull request by ecederstrand**
This makes it easier for automatic license checkers to verify the license of this package.

# Pull Request Checklist

Below is a simple checklist but please do not hesitate to ask for assistance!

- [ ] Fork, clone, and checkout the newest version of the code
- [ ] Create a new branch
- [ ] Make necessary code changes
- [ ] Install `black` (i.e., `python -m pip install black` or `conda install -c conda-forge black`)
- [ ] Install `flake8` (i.e., `python -m pip install flake8` or `conda install -c conda-forge flake8`)
- [ ] Install `pytest-cov` (i.e., `python -m pip install pytest-cov` or `conda install -c conda-forge pytest-cov`)
- [ ] Run `black .` in the root stumpy directory
- [ ] Run `flake8 .` in the root stumpy directory
- [ ] Run `./setup.sh && ./test.sh` in the root stumpy directory
- [ ] Reference a Github issue (and create one if one doesn't already exist)

### CODE REVIEW

**Comment by seanlaw** [comment]
@ecederstrand Thank you for this PR. I'm not well versed in Python license metadata best practices so can you please direct me to some relevant "license checkers"? I'm having a hard time finding consensus on what is preferred here. Maybe you have some thoughts/ideas?

Additionally, would it make sense to also update:

```
"License :: OSI Approved",
```

to

```
"License :: OSI Approved :: BSD-License",
```

**Comment by ecederstrand** [comment]
The license checkers I've used don't mandate which licenses should be approved, let alone their spelling. It's up to the user to provide a list of strings to approve.

Internally in my department, we accept everything approved by OSI, so we feed our license checker with the licenses listed at https://opensource.org/licenses/alphabetical.. It's a lot easier for us if the license metadata of a package we install spells the license name exactly as stated in that list.

While https://pypi.org/classifiers/ only mentions `BSD-License`, this exact name usually refers to the old [4-clause BSD license](https://en.wikipedia.org/wiki/BSD_licenses#4-clause_license_(original_%22BSD_License%22)) which would not be correct in this case. I've updated the classifiers section with the same license name as my original patch. I don't know of any rules stating that the classifiers section must only contain classifiers exactly as listed at https://pypi.org/classifiers/

**Comment by seanlaw** [comment]
Thank you @ecederstrand !

**Comment by seanlaw** [comment]
I just tried to upload to PyPI and am receiving a:

```
Invalid value for classifiers. Error: Classifier 'License :: OSI Approved :: 3-clause BSD License' is not a valid classifier.
```

So, I changed the `setup.py` file back to:

```
"License :: OSI Approved :: BSD License",
```

**Comment by ecederstrand** [comment]
Thanks for the heads-up! Having the official name in the `license` attribute works fine with us.

**Pull request merged**
