### PR TITLE
Fixed #858 OpenMP Missing in Github Actions MacOS

### LINKED ISSUE #858: OpenMP Missing in Github Actions MacOS
In this [Github Actions run](https://github.com/TDAmeritrade/stumpy/actions/runs/4889389944/jobs/8727874737#step:10:205), we are seeing:

```
Numba workqueue threading layer is terminating: Concurrent access has been detected.

 - The workqueue threading layer is not threadsafe and may not be accessed concurrently by multiple threads. Concurrent access typically occurs through a nested parallel region launch or by calling Numba parallel=True functions from multiple Python threads.
 - Try using the TBB threading layer as an alternative, as it is, itself, threadsafe. Docs: https://numba.readthedocs.io/en/stable/user/threading-layer.html
```

which has happened before in this issue #705 and resolved by PR #706

### PR DESCRIPTION
**Pull request by NimaSarajpoor**
See #858 OpenMP Missing in Github Actions MacOS

### CODE REVIEW

**Comment by NimaSarajpoor** [comment]
Related: https://github.com/TDAmeritrade/stumpy/issues/708

**Comment by NimaSarajpoor** [comment]
@seanlaw 
If necessary, please edit the name of this PR.

**Comment by seanlaw** [comment]
@NimaSarajpoor Are you trying to address [this failure](https://github.com/TDAmeritrade/stumpy/actions/runs/4889389944/jobs/8727874737#step:10:205)?

```
Numba workqueue threading layer is terminating: Concurrent access has been detected.

 - The workqueue threading layer is not threadsafe and may not be accessed concurrently by multiple threads. Concurrent access typically occurs through a nested parallel region launch or by calling Numba parallel=True functions from multiple Python threads.
 - Try using the TBB threading layer as an alternative, as it is, itself, threadsafe. Docs: https://numba.readthedocs.io/en/stable/user/threading-layer.html
```

I think this is related to [something that we had addressed earlier](https://numba.discourse.group/t/terminating-nested-parallel-kernel-launch-detected-the-workqueue-threading-layer-does-not-supported-nested-parallelism/1621/7) but seems to have come back again. For MacOS, we should be using openMP and this should be reflected in the output of `numba -s` (see the `Show Full Numba Environment` section of the Github workflow):

```
__Threading Layer Information__
TBB Threading Layer Available                 : False
+--> Disabled due to Unknown import problem.
OpenMP Threading Layer Available              : True
+-->Vendor: Intel
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.
```

Note the line that says `OpenMP Threading Layer Available              : True`. However, in [your failed CI](https://github.com/TDAmeritrade/stumpy/actions/runs/4889389944/jobs/8727874737#step:9:82) we are seeing that openMP is not being used and only workqueue (which is not threadsafe) is being used instead:

```
__Threading Layer Information__
TBB Threading Layer Available                 : False
+--> Disabled due to Unknown import problem.
OpenMP Threading Layer Available              : False
+--> Disabled due to Unknown import problem.
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.
```

Previously, I had to figure out how to get Github Action's MacOS to use OpenMP by adding a new section to the workflow (see `Link OpenMP` section in workflow) but it appears that it is broken again and `numba` is once again not able to find openMP.

**Comment by seanlaw** [comment]
@NimaSarajpoor I'm going to try a few things and push it to this branch

**Comment by NimaSarajpoor** [comment]
> @NimaSarajpoor Are you trying to address [this failure](https://github.com/TDAmeritrade/stumpy/actions/runs/4889389944/jobs/8727874737#step:10:205)?

I noticed [this error message](https://github.com/TDAmeritrade/stumpy/actions/runs/4889389944/jobs/8727874737#step:10:139) and then I was reading web and noticed that to submit a function to scheduler, the function needs to return consistent output. I confess that I should have read the error more carefully and only search for a solution for that exact error. (And, I also need to increase my knowledge in parallel computing :smile: )


> I think this is related to [something that we had addressed earlier](https://numba.discourse.group/t/terminating-nested-parallel-kernel-launch-detected-the-workqueue-threading-layer-does-not-supported-nested-parallelism/1621/7) but seems to have come back again.
> 
> See issue #705 and PR #706
> 
> For MacOS, we should be using openMP and this should be reflected in the output of `numba -s` (see the `Show Full Numba Environment` section of the Github workflow):

Just going through your [discussion in numba discourse](https://numba.discourse.group/t/terminating-nested-parallel-kernel-launch-detected-the-workqueue-threading-layer-does-not-supported-nested-parallelism/1621/5).  A very interesting read!  

> Previously, I had to figure out how to get Github Action's MacOS to use OpenMP by adding a new section to the workflow (see `Link OpenMP` section in workflow) but it appears that it is broken again and `numba` is once again not able to find openMP.

I see! Thank you @seanlaw  for your thorough explanation!

**Comment by NimaSarajpoor** [comment]
@seanlaw 

> P.S. Fixing the `fastmath` (assuming it is wrong) is good but is unlikely the root of the problem here so we may want to split things up rather than conflating them.

You are absolutely correct! I can undo the change and push the commit. We can take care of `fastmath` later in a seperate PR.

**Comment by seanlaw** [comment]
> You are absolutely correct! I can undo the change and push the commit. We can take care of fastmath later in a seperate PR.

It's okay, I think this is ready to merge. Thanks for your help @NimaSarajpoor !

**Comment by NimaSarajpoor** [comment]
> It's okay, I think this is ready to merge. Thanks for your help @NimaSarajpoor !

LOL.... I pushed the commit and the read your message! Sorry about that.

**Comment by seanlaw** [comment]
No worries

**Pull request merged**
