### PR TITLE
Fixed #562 Added parameter atol to motifs/_motifs and docstring

### LINKED ISSUE #562: Missing Parameter in `motifs` Docstring
`motifs` docstring is missing the `atol` parameter description:

https://stumpy.readthedocs.io/en/latest/api.html#motifs

### PR DESCRIPTION
**Pull request by NimaSarajpoor**
* add description of atol to docstring
* pass atol to `_motifs( )` when it is called by the function `motifs( )`

### CODE REVIEW

**Comment by seanlaw** [comment]
Thank you @NimaSarajpoor.  I will merge this once the tests pass

**Comment by seanlaw** [comment]
@NimaSarajpoor I could be wrong but I believe that if you name the PR with `Fixed #IssueNumber` then it will automatically close that issue number when this PR is merged. I don't know what happens if there is additional text between the `Fixed` and `#IssueNumber` (i.e., I don't know if Github is smart enough to know how to handle that). The convention is the word `Fixed` followed directly by `#IssueNumber`. I've updated the title of this (and the other) PR accordingly.

**Comment by NimaSarajpoor** [comment]
@seanlaw 
That is good to know! I did not know about it before! I will consider it from now on. 

Btw, I think I added atol to `_motifs` (not `match` which is what title shows). If I am missing something, please ignore this.

**Comment by seanlaw** [comment]
Thanks for handling this @NimaSarajpoor!

**Pull request merged**
