### PR TITLE
First time tutorial

### PR DESCRIPTION
**Pull request by JosephTLucas**
# Pull Request Checklist

Here's the tutorial notebook, Sean. Where possible, I tried to link to existing STUMPY or GitHub documentation so that everything stays current. Confirmed that Sphinx built the html on my machine.

Issue #246 

Below is a simple checklist but please do not hesitate to ask for assistance!

- [x] Fork, clone, and checkout the newest version of the code
- [x] Create a new branch
- [x] Make necessary code changes
- [x] Install `black` (i.e., `python -m pip install black` or `conda install black`)
- [x] Install `flake8` (i.e., `python -m pip install flake8` or `conda install flake8`)
- [x] Install `pytest-cov` (i.e., `python -m pip install pytest-cov` or `conda install pytest-cov`)
- [x] Run `black .` in the root stumpy directory
- [x] Run `flake8 .` in the root stumpy directory
- [x] Run `./setup.sh && ./test.sh` in the root stumpy directory
- [x] Reference a Github issue (and create one if one doesn't already exist)

### CODE REVIEW

**Comment by seanlaw** [comment]
@JosephTLucas Thanks for pulling this together! Overall, I really like the tone and the content. Here are a few comments that you might find helpful:

- Can we change "Here's everything you should need to know to get started" to "Here are some things that will help you get started"
- I think we can remove ", but some projects use GitLab or other solutions" as it feel distracting since STUMPY is not using Gitlab
- I think "peaked behind the curtain" should "peek"
- Change "Now, get to work!" to "Now, let's get to work!"
- I don't understand what this sentence means: "Next, install the dependencies using the From source instructions. " It isn't clear what the highlighted "From source" instructions is referring to
- I think, technically/loosely, `flake8` is a linter that checks the style and quality of the code while `black`  ensures that the code formatting is consistent throughout the codebase (i.e., style/quality vs formatting)

**Comment by JosephTLucas** [comment]
As always, great recommendations, Sean!

**Comment by seanlaw** [comment]
Everything looks good. I'll add it to the docs. Thank you @JosephTLucas!

**Comment by JosephTLucas** [comment]
That makes sense to me.  It didn't really fit with the rest of the tutorials, but I was trying to maintain consistency.

**Pull request merged**
