### PR TITLE
Fix #880 Add param isconstant to gpu_ostinato and gpu_stimp

### LINKED ISSUE #880: Add Ts_subseq_isconstant to gpu_ostinato
Currently the `Ts_subseq_isconstant` parameter is missing from `gpu_ostinato` and needs to be added

### PR DESCRIPTION
**Pull request by NimaSarajpoor**

### CODE REVIEW

**Comment by NimaSarajpoor** [comment]
[update] `gpu_ostinato` is tested on colab and all tests are passing.

**Comment by NimaSarajpoor** [comment]
[update]
BOTH `gpu_stimp` and `gpu_ostinato` are tested and their unit tests are passing.

@seanlaw 
I think it is ready for your review.

**Comment by seanlaw** [comment]
Thanks @NimaSarajpoor for this PR! Once the foundational work (which you did) is done, the rest becomes so much easier/nicer to implement! Looks great

**Comment by NimaSarajpoor** [comment]
@seanlaw 
Indeed!

**Pull request merged**
