### PR TITLE
Investigate prange

### PR DESCRIPTION
**Pull request by NimaSarajpoor**
To keep track of my investigation on numba `prange`

---

**some tasks to do:**

* try to convert nested loops `range-prange` to `range-range` (one by one)
* check this issue: https://github.com/numba/numba/issues/2477

### CODE REVIEW

**Comment by NimaSarajpoor** [comment]
@seanlaw 
is [this test failure](https://github.com/TDAmeritrade/stumpy/actions/runs/3380946377/jobs/5614300662) related to `prange`? (Is this related to numba? or dask?)

**Comment by seanlaw** [comment]
> @seanlaw is [this test failure](https://github.com/TDAmeritrade/stumpy/actions/runs/3380946377/jobs/5614300662) related to `prange`? (Is this related to numba? or dask?)

> Terminating: Nested parallel kernel launch detected, the workqueue threading layer does not supported nested parallelism. Try the TBB threading layer.

Yes, this was the problem that I was telling you about that only affects MacOS. It'll take me some time to find a solution.

**Comment by seanlaw** [comment]
@NimaSarajpoor Please pull the latest changes/commits into your branch

**Comment by NimaSarajpoor** [comment]
I am going to close this branch as I believe the problem is already resolved.

**Pull request closed without merging**
