### PR TITLE
Update github_actions

### PR DESCRIPTION
**Pull request by NimaSarajpoor**
(Temporary PR) to see if I can fix this: https://github.com/TDAmeritrade/stumpy/actions/runs/3442657454/jobs/5743453327#step:1:35

### CODE REVIEW

**Comment by NimaSarajpoor** [comment]
@seanlaw 
This is completely new to me :) I assume you use v2/v3 (setting of github action in branch `main`) instead of v3/v4 as it is safer. Also, I read that even if I run the github actions with the settings of branch `main`, again, [this error](https://github.com/TDAmeritrade/stumpy/actions/runs/3442657454/jobs/5743453327#step:1:35) might get disappear :) 

I just wanted to see if v3/v4 works or not! Hence, please feel free to close this PR!

---

btw, have you noticed this warning [here](https://github.com/TDAmeritrade/stumpy/actions/runs/3442657454)?

It says:
> [unit-testing (ubuntu-latest, 3.8)](https://github.com/TDAmeritrade/stumpy/actions/runs/3442657454/jobs/5743453137)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2

And, according to this:
https://github.com/actions/checkout/compare/v2.4.2...v3.0.2#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R17-R18

`actions/checkout@v3` runs on Node.js 16. 

----

Again, this is all new to me! So, if I said something nonsense, please forgive me 😄

**Comment by seanlaw** [comment]
Cool. I'm probably behind on using v3/v4 so this is a welcome change if it is stable. I did notice the Nodejs warnings but ignored them since I didn't think we would be affected but I see your point now. Initially, Github Actions failed from the changes to the workflow but they seemed to have passed when I re-ran them. I'm going to re-run it a few times just to test out how stable/consistent it is.

**Comment by seanlaw** [comment]
@NimaSarajpoor I don't see any additional warnings. Maybe it's clean enough to merge? What do you think?

**Comment by NimaSarajpoor** [comment]
> if it is stable.

Yeah...I totally understand. That is what I guessed, that you wanted to go with safer option (more stable). 

> @NimaSarajpoor I don't see any additional warnings. Maybe it's clean enough to merge? What do you think?

Yeah....It seems there should be no problem :) 

Just out of curiosity, is this stable? If I am not mistaken, I can see [the latest release](https://github.com/actions/checkout/releases) is v2.5.

**Comment by seanlaw** [comment]
> I can see [the latest (stable?) release](https://github.com/actions/checkout/releases) is v2.5.

Yeah, I noticed that too! Not sure why "latest release" is `v2.5` but they call it `@v3` in the Github Workflow. I'll merge it and we'll keep an eye on it and revert back if we need to.

**Comment by NimaSarajpoor** [comment]
> Yeah, I noticed that too! Not sure why "latest release" is `v2.5` but they call it `@v3` in the Github Workflow

yeah.... see https://github.com/actions/checkout/issues/831

**Pull request merged**
