### PR TITLE
Refactor test files 

### PR DESCRIPTION
**Pull request by Ninimama**
Move naive implementation to the top of test files (Ref #434) 

# Pull Request Checklist

Below is a simple checklist but please do not hesitate to ask for assistance!

- [x] Fork, clone, and checkout the newest version of the code
- [x] Create a new branch
- [x] Make necessary code changes
- [x] Install `black` (i.e., `python -m pip install black` or `conda install -c conda-forge black`)
- [x] Install `flake8` (i.e., `python -m pip install flake8` or `conda install -c conda-forge flake8`)
- [x] Install `pytest-cov` (i.e., `python -m pip install pytest-cov` or `conda install -c conda-forge pytest-cov`)
- [x] Run `black .` in the root stumpy directory
- [x] Run `flake8 .` in the root stumpy directory
- [x] Run `./setup.sh && ./test.sh` in the root stumpy directory
- [x] Reference a Github issue (and create one if one doesn't already exist)

### CODE REVIEW

**Comment by seanlaw** [comment]
Thank you!

**Comment by seanlaw** [comment]
FYI, I just added a new function to `test.sh` called `check_naive` that checks to see if there are any naive implementations that come after a test. If there is, `test.sh` exits with an error

**Comment by Ninimama** [comment]
I had this idea but not the knowledge to implement it. This is great!

**Comment by seanlaw** [comment]
> I had this idea but not the knowledge to implement it. This is great!

I didn't know either but just played around and threw something together. :)

**Pull request merged**
