### PR TITLE
Fix #1013 set param `T_subseq_isconstant ` to default `None` in `core.process_isconstant`

### LINKED ISSUE #1003: Improve MSTUMP Performance
For longer time series, multi-dimensional matrix profile computation seems slow. We should explore ways to improve the algorithm. 

For example, if the user wants ALL dimensions (instead of a subset-`k` dimensions) then it may be possible to avoid some calculations.

### LINKED ISSUE #1013: Parameter `T_subseq_isconstant` in `core.process_isconstant` should be set to `None` as default
The docstring says:
```
T_subseq_isconstant : numpy.ndarray, function, or list, default None 
```

However, the parameter is not set to None.

https://github.com/TDAmeritrade/stumpy/blob/3077d0ddfb315464321dc86f8ec3bf2cab9ce3b1/stumpy/core.py#L4224-L4244

### PR DESCRIPTION
**Pull request by NimaSarajpoor**
see #1013

### CODE REVIEW

**Comment by NimaSarajpoor** [comment]
@seanlaw 
I am thinking of adding a test function just for the default mode, i.e. `T_subseq_isconstant` is set to `None`.

**Comment by seanlaw** [comment]
@NimaSarajpoor is this ready to be merged?

**Comment by NimaSarajpoor** [comment]
@seanlaw 
Yes. Please merge it. Thank you!

**Comment by seanlaw** [comment]
@NimaSarajpoor Thanks you for this PR!

**Pull request merged**
