### PR TITLE
Fix mass absolute nan

### LINKED ISSUE #286: mass_absolute returns NaN for some negative time-series
I found this while playing with the PAMAP dataset. Haven't been able to reproduce this with random numbers, so here's the relevant data and code.
```python
Q = np.array([-13.09, -14.1 , -15.08, -16.31, -17.13, -17.5 , -18.07, -18.07,
       -17.48, -16.24, -14.88, -13.56, -12.65, -11.93, -11.48, -11.06,
       -10.83, -10.67, -10.59, -10.81, -10.92, -11.15, -11.37, -11.53,
       -11.19, -11.08, -10.48, -10.14,  -9.92,  -9.99, -10.11,  -9.92,
        -9.7 ,  -9.47,  -9.06,  -9.01,  -8.79,  -8.67,  -8.33,  -8.  ,
        -8.26,  -8.  ,  -7.54,  -7.32,  -7.13,  -7.24,  -7.43,  -7.93,
        -8.8 ,  -9.71])
print(stumpy.core.mass_absolute(Q, Q))
```
I get `nan`, but of course it should be `0`. The problem is some float imprecision in `_mass_absolute` that leads to negative values that can't be properly `np.sqrt`ed.

Easy to fix, of course. A test for this edge case should be added as well.

### PR DESCRIPTION
**Pull request by DanBenHa**
Fixes #286 

# Pull Request Checklist

Below is a simple checklist but please do not hesitate to ask for assistance!

- [x] Fork, clone, and checkout the newest version of the code
- [x] Create a new branch
- [x] Make necessary code changes
- [x] Install `black` (i.e., `python -m pip install black` or `conda install -c conda-forge black`)
- [x] Install `flake8` (i.e., `python -m pip install flake8` or `conda install -c conda-forge flake8`)
- [x] Install `pytest-cov` (i.e., `python -m pip install pytest-cov` or `conda install -c conda-forge pytest-cov`)
- [x] Run `black .` in the root stumpy directory
- [x] Run `flake8 .` in the root stumpy directory
- [x] Run `./setup.sh && ./test.sh` in the root stumpy directory
- [x] Reference a Github issue (and create one if one doesn't already exist)

### CODE REVIEW

**Comment by seanlaw** [comment]
@DanBenHa Thank you for the PR! I couldn't find much information on when negative values may occur except for one article that simply set those values to zero before taking the square root. I am wondering if there are situations where setting the negative values to zero is wrong?

Otherwise, everything else looks good and this should be ready to merge.

**Comment by DanBenHa** [comment]
> I am wondering if there are situations where setting the negative values to zero is wrong?

Good question. I don't know. But that would imply calculating a complex value for the distance of two real-valued vectors. Would that make sense?

**Comment by seanlaw** [comment]
> Good question. I don't know. But that would imply calculating a complex value for the distance of two real-valued vectors. Would that make sense?

Since negative values imply some sort of deficiency in the numerical precision, I think what I'm really asking is if there might be situations where the amplitude of the negative value may be indicative of something that is a lot worst (while a small, near zero amplitude is due to numerical precision).  Just thinking out loud here though :)

**Comment by DanBenHa** [comment]
> Since negative values imply some sort of deficiency in the numerical precision, I think what I'm really asking is if there might be situations where the amplitude of the negative value may be indicative of something that is a lot worst (while a small, near zero amplitude is due to numerical precision). Just thinking out loud here though :)

I see. I guess it could be indicative of problems in the computation of `Q_squared`, `T_squared` and `QT`, so primarily in the functions `rolling_is_finite`, `sliding_dot_product` and `rolling_window`.

**Comment by seanlaw** [comment]
Okay, I spent most of my morning looking for an ideal solution and, while there were many discussions, there were no obvious solutions

**Comment by DanBenHa** [comment]
> Okay, I spent most of my morning looking for an ideal solution and, while there were many discussions, there were no obvious solutions

Haha, reminds me of some of my mornings ;)

Thanks for merging and the interesting question raised.

**Pull request merged**
