### PR TITLE
Topk_matrixprofile Investigator

### PR DESCRIPTION
**Pull request by NimaSarajpoor**
This PR is to investigate the time-out failure in PR #595. 

This is how I created this branch:
```
# in branch main
git branch -c [old branch] [new branch]
git checkout [new branch]

# so, while  I am in this new branch
git reset --hard HEAD~[number]
```

Note that I did not `git merge main` after this. It seems the changes in `main` are preserved already. So, later, we can skip the commits regarding the `git merge main`.

### CODE REVIEW

**Comment by NimaSarajpoor** [comment]
@seanlaw 
Apparently, the `git branch -c` does not create a completely separated branch, and it seems the new branch is created off the old branch. Please see screenshot below.

image

So, I think it would be similar:
```
git checkout -b [new_branch]  76f97cb # which is the highlighted commit in image above
```

I think this should work for us. I mean...I can now do `git cherry-pick [commit] ` (or any other approach?!) to add commits one by one from this point. I hope this works.

**Comment by seanlaw** [comment]
@NimaSarajpoor In its current state, can you help me understand how this PR is different/same as PR #595? It looks to me like the files are all the same?

**Comment by NimaSarajpoor** [comment]
> In its current state, can you help me understand how this PR is different/same as PR #595? It looks to me like the files are all the same?

So, I did not start from scratch. I knew that a few `push`es ago, things were good. So, now my NEW branch is at that point were things were good. Even if the files look like the same, some last changes to those files are retrieved. For instance, if you take a look at `tests/test_stump.py`, you can see the KNN test function is just for k=3 and not `range(1,4)`. Or, in `stumpy/gpu_stump.py`, the `gpu_searchsorted_left/right` are decorated with `@jit` (and not `@jit(device=True)`).

**Comment by seanlaw** [comment]
@NimaSarajpoor I ask because all of the tests have now passed (perhaps this was expected). Please go ahead ahead and add one commit at a time, allow the tests to run, and let's see where it breaks.

**Comment by NimaSarajpoor** [comment]
Sure. If I see a commit results in failure. I will reset it, and then try to see if I can break down that specific commit to smaller commits so we can isolate the "bad" change.

**Comment by NimaSarajpoor** [comment]
I got into a `detached head` problem where things got weird and the changes got disappeared. So, I had to retrieve it! This is basically just to make sure everything is normal again. 

(I am now using `git show` to find changes in each commit and apply those changes to the files in this current branch)

**Comment by seanlaw** [comment]
The test passed. Please keep adding incrementally until tests fail

**Comment by seanlaw** [comment]
@NimaSarajpoor I just made some changes to `test.sh` so that:

1. The coverage test results have been split up so that we have a little bit better visibility into how long each test is taking (similar to unit tests)
2. I've updated `./test.sh custom` to be a lot more user friendly from the command line so you shouldn't need to change the `test.sh` file and so that you can quickly do:

```
./test.sh custom tests/test_stump.py

# Run multiple test files
./test.sh custom tests/test_stump.py tests/test_stumped.py

# Run 1000 rounds (default is 10 rounds)
./test.sh custom 1000 tests/test_stump.py

# Run a specific test within a test file
./test.sh custom tests/test_stump.py::test_stump_self_join
```

**Comment by NimaSarajpoor** [comment]
@seanlaw 
I know that I should do `k in  range(2, 4)` as `k=1` is already tested; however, I am trying to replicate the commits so we do not miss anything. 

(Also, for now, I am skipping the commits in which I just fixed a typo or rename a function).

**Comment by seanlaw** [comment]
> @seanlaw I know that I should do `k in range(2, 4)` as `k=1` is already tested; however, I am trying to replicate the commits so we do not miss anything.
> 
> (Also, for now, I am skipping the commits in which I just fixed a typo or rename a function).

Sounds good. Thanks for the heads up

**Comment by seanlaw** [comment]
Great! Tests are still passing

**Comment by NimaSarajpoor** [comment]
I will push the next commit in a couple of hours.

**Comment by NimaSarajpoor** [comment]
@seanlaw 
I think we are going to see failure in this last commit as it is related to a function that is used in `stumped`, and I believe the remaining commits are just minor changes. 

So, if we do not see any failure this time, I will push the few remaining commits together.

**Comment by seanlaw** [comment]
> I do not know why tests are passing.

@NimaSarajpoor I'd bet that it is because of the two things that I did:

1. Switch to `2022.5.0` for both `dask` and `distributed`
2. Split the coverage tests into individual tests

Let me revert the first one (i.e., allow `2022.5.2` to be installed) and then have you merge and push to see what happens.

**Comment by NimaSarajpoor** [comment]
@seanlaw 
I also compared the files side by side and it seems they are the same (i.e. I did not miss any commit and all of them are replicated here in this PR).

**Comment by NimaSarajpoor** [comment]
I am planning to delete this branch. Just to be on the safe side, I will back up the files in `stumpy` and `tests`. 

If there is something that I should be aware of regarding this matter, please let me know.

**Comment by seanlaw** [comment]
No, I think it should be okay to delete this branch and close out this PR

**Pull request closed without merging**
