### PR TITLE
Investigate Github Workflow RunTime

### PR DESCRIPTION
**Pull request by NimaSarajpoor**
See: https://github.com/TDAmeritrade/stumpy/issues/982#issuecomment-2224137251

### CODE REVIEW

**Review by seanlaw — COMMENTED** [review]
@NimaSarajpoor The changes look good to me. Can you describe what is actually taking a long time or causing the spike in time?

If this is sufficient, is there a reason why we don't change the tests in `test_ostinato` and `test_aamp_ostinato`?

**Comment by NimaSarajpoor** [comment]
@seanlaw 
The spike is coming from calling `gpu_ostinato`. 

I think the only difference between  `test_ostinato` and `test_gpu_ostinato` is the part that we compute the consensus. The former uses `ostinato` and the latter uses `gpu_ostinato`. These two functions themselves are similar and the only difference is that the former calls `stump` and the latter calls `gpu_stump`.  When we turn off CUDA and JIT, `stump` algo should be faster. For example, on my Mac, for the window size 20 and the input list `Ts` that contains time series of lengths 512 and 1024, the `gpu_ostinato` takes 60 sec while `ostinato` takes 3 sec. I did not dig further.

**Comment by seanlaw** [comment]
Shall I merge this now?

**Comment by NimaSarajpoor** [comment]
@seanlaw 

> Shall I merge this now?

sure 👍

**Pull request merged**
