### PR TITLE
Clarifying the "Make your Changes" Section

### PR DESCRIPTION
**Pull request by Ninimama**
Regarding Issue #385: Clarifying the "Make your Changes" Section
============================================

# Pull Request Checklist

Below is a simple checklist but please do not hesitate to ask for assistance!

- [x] Fork, clone, and checkout the newest version of the code
- [x] Create a new branch
- [x] Make necessary code changes
- [x] Install `black` (i.e., `python -m pip install black` or `conda install -c conda-forge black`)
- [x] Install `flake8` (i.e., `python -m pip install flake8` or `conda install -c conda-forge flake8`)
- [x] Install `pytest-cov` (i.e., `python -m pip install pytest-cov` or `conda install -c conda-forge pytest-cov`)
- [x] Run `black .` in the root stumpy directory
- [x] Run `flake8 .` in the root stumpy directory
- [x] Run `./setup.sh && ./test.sh` in the root stumpy directory
- [x] Reference a Github issue (and create one if one doesn't already exist)

### CODE REVIEW

**Comment by seanlaw** [comment]
@Ninimama Thank you for updating the notebook. Below, I've provided some edits to your submission:

```
Next, install the dependencies using the From Source Section of the instructions. If you are building STUMPY within a conda environment, then you may consider using the conda.sh shell script which will automatically assist you in installing all of the required dependencies required for testing.  

A good check to make sure everything is working 100% is to run the unit tests. For STUMPY, we have scripts to help you do that. You'll run ./setup.sh && ./test.sh. In some cases, you may notice an uninstallation message for STUMPY but don't worry. This happens if you have had previously installed STUMPY as the ./setup.sh command first uninstalls any existing version of STUMPY and then it will re-install it again from source (the local, cloned, development version). So, everything should be all set. 

Ideally, you'll see the excellent STUMPY test coverage passing. If things start failing or breaking, you have a dependency problem. There's nothing worse than finding this out after you've made changes. 
```

**Comment by Ninimama** [comment]
@seanlaw 
Thanks for the comment. Will do the changes and push a commit soon

**Comment by Ninimama** [comment]
@seanlaw 
I clarified some parts and pushed the commits. I sometimes use the **bold**  to attract the reader'a attention. Is that okay (in terms of consistency)?

**Comment by seanlaw** [comment]
Thanks for letting me know. I did take a look along the way but wasn't sure if you were ready for comments yet. Let me take a closer look

**Comment by seanlaw** [comment]
@Ninimama I think everything looks good! There are a couple of grammatical corrections but I can handle them after this PR is merged. Thank you for working on this and congratulations on your first STUMPY PR! 👍

**Comment by Ninimama** [comment]
@seanlaw 
Thanks, Sean, for your constructive feedback and support. It has been a good and fun experience.

**Pull request merged**
